### ISSUE TITLE
python3.8 启动时遇到问题

### ISSUE THREAD

**Issue by RainDrop02** [lonive/campushoy-gravedigger#1]
root@iZ2zehmy984xzq25kheomwZ:/opt/campushoy-gravedigger# python3 main.py
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    main()
  File "main.py", line 6, in main
    cookie = login.get_cookie()
  File "/opt/campushoy-gravedigger/login.py", line 27, in get_cookie
    redirect_url = res.headers['Location']
  File "/usr/local/lib/python3.8/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
在自己家电脑能正常运行，但是换到服务器上面这个就报错了，家里电脑时python3.10的。服务器是Ubuntu  20.04 64位，python3.8

**Comment by RainDrop02** [comment]
尝试升到python3.9报这个错误`Traceback (most recent call last):
  File "/opt/campushoy-gravedigger/main.py", line 14, in <module>
    main()
  File "/opt/campushoy-gravedigger/main.py", line 6, in main
    cookie = login.get_cookie()
  File "/opt/campushoy-gravedigger/login.py", line 27, in get_cookie
    redirect_url = res.headers['Location']
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'`

**Comment by lonive** [comment]
在服务器端执行命令：
```shell
curl -L https://neau.campusphere.net/iap/login?service=https://neau.campusphere.net/portal/login
```
如果返回的内容包含"**您的请求疑似攻击行为！**"，则代表服务器端的请求被今日校园使用的华为云 WAF 拦截。目前已知腾讯云和阿里云的部分 IP 段被 WAF 标记，不能进行签到。

**Comment by RainDrop02** [comment]
那就对了，应该是服务器的问题，谢谢学长了
